from . import hr_employee
from . import hr_salary_rule
from . import bareme_anciennete
from . import hr_abbatement
from . import hr_contract
from . import hr_payslip
from . import hr_payroll_structure
from . import res_config_settings
from . import hr_absence_type
from . import hr_absences
from . import hr_heures_supp
from . import hr_heures_supp_type
from . import hr_primes
from . import hr_primes_type
from . import hr_prets
from . import hr_rappel
from . import hr_rappel_type
from . import hr_avance
from . import hr_conge
from . import hr_leave_type
from . import res_company