# -*- coding: utf-8 -*-
{
	'name': "paie Oxycode",
	'category': 'ressource humaine',
	'author': "Oxycode",
	'version': '1.0',
	'license': "LGPL-3",

	# any module necessary for this one to work correctly
	'depends': ['hr_contract', 'om_hr_payroll', 'oxy_attendance_leaves', 'report_xlsx'],

	# always loaded
	'data': [
		#'views/menu.xml',
		'security/ir.model.access.csv',
		'report/reports.xml',
		'views/hr_employee.xml',
		'views/hr_abbatement.xml',
		'views/hr_contract.xml',
		'views/bareme_anciennete.xml',
		'views/hr_payslip.xml',
		'data/oxy_paie_data.xml',
		'data/hr_absence_type.xml',
		'data/hr_heure_supp_type.xml',
		'data/hr_primes_types.xml',
		'data/hr_rappels_types.xml',
		'views/hr_absence_type_view.xml',
		'views/hr_primes_type.xml',
		'views/hr_rappel_type.xml',
		'views/assignment_by_department_view.xml',
		'views/hr_primes_view.xml',
		'views/hr_rappel_view.xml',
		'views/hr_salary_rule_view.xml',
		'views/hr_payroll_structure_view.xml',
		'views/res_config_settings_views.xml',
		'views/hr_absences_view.xml',
		'views/hr_heures_supp_view.xml',
		'views/hr_heures_supp_types.xml',
		'views/hr_prets.xml',
		'views/journal_paie_views.xml',
		'report/bulletin_de_paie.xml',
		'views/payroll_centralizer.xml',
		'report/payroll_centralizer.xml',
		'views/hr_avance_views.xml',
		'data/ir_cron_data.xml',
		'views/hr_conge_views.xml',
		'data/hr_leave_type.xml',
		'data/ir_sequence.xml',
		'views/r301_bis_views.xml',
		'views/rapport_cnas_views.xml',
		'views/report_cnas.xml',
		'views/report_journal_paie.xml',
		'views/res_company_views.xml',
		'views/rap_menu.xml',
	],

	'installable': True,
	'auto_install': False,
	'application': False,
}